name: Generate terraform docs
on: [push, pull_request]
permissions:
  contents: read
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    
    - name: Retry fetching repository
      run: |
        for i in {1..5}; do
          git fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +refs/heads/resource-type-suffix-support*:refs/remotes/origin/resource-type-suffix-support* +refs/tags/resource-type-suffix-support*:refs/tags/resource-type-suffi && break || sleep 15;
        done

    - name: Render terraform docs inside the USAGE.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@aeae0038ed47a547e0c0fca5c059d3335f48fb25 
      with:
        working_dir: .
        output_file: README.md
        output_method: inject
        git_push: 'true'